### ISSUE TITLE
Number of jobs in queue before mine?

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-framework#106]
Is there a way to find out how many jobs are in the queue before mine?

**Comment by capitancambio** [comment]
You can see your jobs, but not someone else's, unless you're admin so you
can see everyone's.

**Comment by josteinaj** [comment]
For the Web UI we could add support for some kind of "X currently running jobs, Y queued jobs in front of this, Z jobs queued in total" message of some sort. Although it might be more neat to have it in the engine?

**Comment by bertfrees** [comment]
@capitancambio OK that's what I thought was the case. 

I was just thinking, it could improve user friendliness if people have an idea how long they have to wait for something. A psychological thing.

**Comment by capitancambio** [comment]
I think it's a good idea, I'll create an entry point for that.

**Comment by capitancambio** [comment]
Closing the issue here and opening one in the issues repo https://github.com/daisy/pipeline-issues/issues/475
