### ISSUE TITLE
Enable "option descriptor" services to allow dynamic option value sets

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-framework#73]
Module authors can register a new type of service "Option Type Descriptor" that will described the type (e.g. allowed values) of an option. The framework can then call this service and expose it to the client via the script XML object.

This will be used to dynamically enumerate the list of available TTS voices.

**Comment by bertfrees** [comment]
This was fixed by https://github.com/daisy/pipeline-framework/pull/84.
