### ISSUE TITLE
Update calabash-custom-steps to the new Calabash API

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-framework#78]
The custom `cx:message` step implementation does not build with Calabash 1.0.23. The few modules that still use this message step (like NLP modules) fail at runtime.

We should update the implementation, and possibly see if this custom overridden implementation is stil needed.

**Comment by bertfrees** [comment]
The module was removed completely. See 243ffddae00e896cbce5670288a8efec50a9990b and https://github.com/daisy/pipeline-assembly/commit/e35d2862fed39f73795d817ae41ed59679acd271. It looks like no modules use `cx:message` anymore (see for example https://github.com/daisy/pipeline-mod-nlp/commit/607841efbdbfdf6421bf823d58eda5bebc9f297f) so I assume I can close this issue.
